name: Sync with Other Repos

on:
  push:
    branches:
      - master
     
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

     

      - name: Push to Other Developers
        run: |
          for repo in git@github.com:SerdiukVladyslav/TestVlad.git; do
            git remote add peer $repo || true
            git fetch peer
            git push peer master
          done
