name: Sync with Other Repos

on:
  push:
    branches:
      - master
     
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

     

      
     - name: Push to Other Repositories
        run: |
          # Добавляем удаленный репозиторий
          git remote add peer git@github.com:SerdiukVladyslav/TestVlad.git || true
          # Получаем изменения из удаленного репозитория
          git fetch peer
          # Отправляем ветку master в ветку main удаленного репозитория
          git push peer master:main
         
